version: "3"
services:
  grafana:
    image: grafana/grafana:6.7.2
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - monitoring
    links:
      - "prometheus:prometheus"
  prometheus:
    image: prom/prometheus:v2.17.1
    ports:
      - 9090:9090
    depends_on:
      - backend
    volumes:
      - "./prometheus.yaml:/etc/prometheus/prometheus.yml"
    networks:
      - monitoring
    links:
      - "backend:backend"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    networks:
      - monitoring
  import-boards:
    build:
      context: ./boards
      dockerfile: Dockerfile
    depends_on:
      - grafana
    volumes:
      - "./boards/key:/opt/key"
      - "./boards/import/:/opt/import"
    networks:
      - monitoring
    links:
      - "grafana:grafana"
networks:
  monitoring:
